# Generated by Django 2.1.3 on 2018-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vistara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_no', models.IntegerField()),
                ('f_origin', models.CharField(max_length=40)),
                ('f_destPlace', models.CharField(max_length=40)),
                ('f_destTime', models.CharField(max_length=50)),
            ],
        ),
    ]
