# Generated by Django 2.1.3 on 2018-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app36', '0002_auto_20181204_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='makemytrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_number', models.CharField(max_length=50)),
                ('f_departuretime', models.CharField(max_length=50)),
                ('f_departureplace', models.CharField(max_length=50)),
                ('f_arrivaltime', models.CharField(max_length=50)),
                ('f_arrivalplace', models.CharField(max_length=50)),
            ],
        ),
    ]
