# Generated by Django 2.1.3 on 2018-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app36', '0003_makemytrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='yatra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_number', models.CharField(max_length=50)),
                ('f_departuretime', models.CharField(max_length=50)),
                ('f_arrivaltime', models.CharField(max_length=50)),
            ],
        ),
    ]
